"""English conversation material for the multi-speaker half of the corpus.

A conversation is a seeded random run of these exchanges: one speaker asks,
another answers, and (with three speakers) the third sometimes reacts. Like
``sentences.py``, lines avoid digits and names so scores measure the pipeline.
"""

EXCHANGES = [
    ("Did you finish reading the chapter for today?", "Yes, I read it last night, but the second half was difficult."),
    ("What did you think of the lecture this morning?", "It was interesting, especially the part about training data."),
    ("Are you coming to the study group this evening?", "I would like to, but I have to work until late."),
    ("Where should we meet before the exam?", "Let us meet in front of the library a little early."),
    ("Do you understand how cross validation works?", "I think so. You test the model on data it has not seen."),
    ("Why does the model perform badly on new data?", "Because it memorized the training examples instead of learning patterns."),
    ("How long did the homework take you?", "Most of the afternoon, because I made a mistake at the start."),
    ("Could you explain the last example again?", "Of course. We split the data and compare the results."),
    ("Is the professor strict about deadlines?", "Very strict, so please do not submit anything late."),
    ("Have you seen the new schedule for next week?", "Yes, the meeting was moved to the afternoon."),
    ("What is the weather like outside?", "It is cold and windy, so bring a warm jacket."),
    ("Will it rain this weekend?", "The forecast says there will be light rain on Sunday."),
    ("Where did you go on your summer holiday?", "We visited a quiet village near the mountains."),
    ("How was the trip to the coast?", "Beautiful. We walked along the beach every evening."),
    ("Did you take the train or the bus?", "The train, because it is faster and more comfortable."),
    ("Is the museum open on Mondays?", "No, it is closed on Mondays but open the rest of the week."),
    ("What would you like to eat tonight?", "Something simple, maybe soup and fresh bread."),
    ("Can you recommend a good restaurant nearby?", "The small place on the corner serves excellent noodles."),
    ("Do you cook at home very often?", "Almost every day. It is healthier and cheaper."),
    ("Who taught you how to bake bread?", "My grandmother taught me when I was a child."),
    ("Should we buy fruit at the market?", "Yes, the fruit there is fresher than in the supermarket."),
    ("How much water do you drink every day?", "Not enough, I should really drink more."),
    ("Do you exercise before or after work?", "Usually in the morning, before the office opens."),
    ("How did you sleep last night?", "Badly. The neighbors were playing loud music."),
    ("Are you feeling better today?", "Much better, thank you. The rest really helped."),
    ("Did the doctor give you any advice?", "She told me to rest and drink plenty of water."),
    ("Have you ever tried learning a second language?", "Yes, I practice a little every day with an app."),
    ("What is the hardest part of learning a language?", "Speaking with confidence, especially on the phone."),
    ("Do you prefer reading books or watching films?", "Books, because I can imagine the story myself."),
    ("What kind of music do you enjoy?", "Mostly calm music that helps me relax."),
    ("Did you enjoy the concert last night?", "Very much. The orchestra was wonderful."),
    ("Have you visited the new art gallery?", "Not yet, but I heard the paintings are impressive."),
    ("Is your computer working again?", "Yes, the update fixed the problem."),
    ("Did you save a backup of your files?", "Of course, I always keep a copy on another drive."),
    ("Why is the internet so slow today?", "The storm damaged some of the cables in the area."),
    ("Can you help me with this program?", "Sure. Show me the error message first."),
    ("What does this error message mean?", "It means the file could not be found."),
    ("Should I use a stronger password?", "Definitely. Use a long phrase that is easy for you to remember."),
    ("How do solar panels produce electricity?", "They turn sunlight directly into electrical energy."),
    ("Is recycling really worth the effort?", "Yes, it reduces waste and saves natural resources."),
    ("Why are bees so important?", "They pollinate the plants that give us fruit and vegetables."),
    ("What causes the tides in the ocean?", "Mainly the pull of the moon on the water."),
    ("Have you ever seen a whale in the wild?", "Once, from a boat far out at sea."),
    ("Are the mountain roads open in winter?", "No, they are usually closed because of the snow."),
    ("What should we pack for the hike?", "Water, food, a map and a warm layer."),
    ("How far is the lake from here?", "About an hour on foot through the forest."),
    ("Did your team win the match on Saturday?", "Yes, we won in the last few minutes."),
    ("How often does the team practice?", "Twice a week, and more before important games."),
    ("Do you want to play football in the park?", "Maybe later, when it is not so hot."),
    ("When does the next bus leave?", "In ten minutes, from the stop across the street."),
    ("Is the airport far from the city center?", "Not really, the train takes about half an hour."),
    ("Why was the flight delayed?", "There was thick fog early in the morning."),
    ("Did you book a room at the hotel?", "Yes, a room with a view of the lake."),
    ("How was your first day at the new job?", "Busy, but my colleagues were very friendly."),
    ("What do you like most about your work?", "Working with a team that communicates well."),
    ("Are you nervous about the presentation?", "A little, but I have practiced it several times."),
    ("Who is leading the project this year?", "The manager from the design department."),
    ("When is the report due?", "At the end of the week, before the meeting."),
    ("Can we move the meeting to the afternoon?", "That works for me. I will tell the others."),
    ("Did you read the news this morning?", "Only the headlines. Was something important announced?"),
    ("What did the government announce?", "A new plan to improve roads in rural areas."),
    ("Is public transport cheaper than driving?", "Usually, and it is better for the environment too."),
    ("Do you ride your bicycle to work?", "When the weather is good, yes."),
    ("Why did the price of vegetables go up?", "The summer was very dry, so the harvest was small."),
    ("How do you manage to save money?", "I put aside a little every week."),
    ("Would you like to buy a house one day?", "Maybe, but for now renting is easier."),
    ("What are the children doing this afternoon?", "They are building a snowman in front of the school."),
    ("Does your dog like going for walks?", "He loves it, especially near the river."),
    ("Where did you adopt your cat?", "From the animal shelter on the edge of town."),
    ("Have you planted anything in the garden?", "Some herbs and tomatoes on the balcony."),
    ("What is your favorite season?", "Autumn, when the leaves change color."),
    ("Did you see the sunset yesterday?", "Yes, the whole sky turned orange and pink."),
    ("Can you recommend a good book?", "I just finished a novel about a family moving abroad."),
    ("Is the author giving a talk at the bookstore?", "Yes, on Thursday evening, and she will sign copies."),
    ("How do you remember what you read?", "I write a short summary after each chapter."),
    ("Why do you take so many breaks while studying?", "Short breaks help me concentrate for longer."),
    ("What will the final exam cover?", "Everything we have studied this term."),
    ("Are we allowed to use notes during the exam?", "No, and phones must be switched off."),
    ("Did you volunteer at the beach cleanup?", "Yes, we collected many bags of rubbish."),
    ("Is the festival worth visiting?", "Absolutely. People come from many countries."),
    ("Who built the old castle on the hill?", "Nobody knows for sure, but it is very old."),
    ("Why were ancient cities built near rivers?", "Rivers provided water, food and transport."),
    ("What did you learn at the science fair?", "How robots can sort packages very quickly."),
    ("Will artificial intelligence replace many jobs?", "Some jobs will change, and new ones will appear."),
    ("How can engineers make cars use less energy?", "By making them lighter and more efficient."),
    ("Why is good communication so important?", "Because misunderstandings can ruin a project."),
    ("Is it difficult to work in a large team?", "Sometimes, but clear roles make it easier."),
    ("Shall we review the main points before we finish?", "Good idea. Let us go through them one by one."),
    ("Do you have any questions before we end?", "Just one: when is the next session?"),
    ("Thank you for your help today.", "You are welcome. See you next week."),
]

# Short reactions a third speaker can interject after an answer.
REACTIONS = [
    "That makes sense.",
    "I agree with that.",
    "Really? I did not know that.",
    "That is a good point.",
    "I had the same experience.",
    "Interesting, tell me more.",
    "I am not so sure about that.",
    "Exactly what I was thinking.",
    "That sounds wonderful.",
    "Good to know, thank you.",
    "I will remember that.",
    "Same here.",
]
