"""English source sentences for the multilingual regression corpus.

Each language's recording is a seeded random selection of these sentences,
machine-translated into the target language, so every file has an exact
English reference. Sentences deliberately avoid digits (Whisper may write
"three" or "3"), names and rare jargon, so scores measure the pipeline rather
than spelling conventions.
"""

SENTENCES = [
    "Good morning everyone, and welcome to today's lecture.",
    "Today we are going to talk about how machines learn from examples.",
    "A model learns patterns from the training data it is given.",
    "If the model memorizes the training data, it performs poorly on new data.",
    "This problem is called overfitting, and it is very common.",
    "One way to reduce overfitting is to collect more training data.",
    "Another way is to keep the model simple.",
    "Cross validation helps us estimate how well a model will generalize.",
    "Please write down the main ideas in your notebook.",
    "The homework for next week is to evaluate a simple classification model.",
    "The library is open every day until late in the evening.",
    "Many students prefer to study together in small groups.",
    "Reading the chapter before class makes the lecture much easier to follow.",
    "If you have a question, please raise your hand at any time.",
    "The weather today is cold and windy, so bring a warm coat.",
    "It rained heavily last night, and some streets were flooded.",
    "Spring is my favorite season because the flowers begin to bloom.",
    "The train to the city leaves from the main station every morning.",
    "My grandmother taught me how to cook soup with fresh vegetables.",
    "We visited a small village near the mountains during the summer holiday.",
    "The market sells fruit, bread, cheese and fresh fish.",
    "Drinking enough water every day is important for your health.",
    "Regular exercise improves both the body and the mind.",
    "Doctors recommend sleeping well before an important exam.",
    "The museum has a large collection of old paintings and sculptures.",
    "Music can help people relax after a long and stressful day.",
    "The children played football in the park until the sun went down.",
    "Our neighbors adopted a friendly dog from the animal shelter.",
    "The river flows slowly through the valley toward the sea.",
    "Forests provide homes for many animals and clean the air we breathe.",
    "Climate change affects farmers, cities and wildlife around the world.",
    "Solar panels turn sunlight into electricity for homes and schools.",
    "Recycling paper and plastic reduces the amount of waste we produce.",
    "The new bridge will make travel between the two towns much faster.",
    "Engineers must test every design carefully before it is built.",
    "A good scientist always questions the results of an experiment.",
    "The telescope allows us to see distant stars and planets.",
    "The moon has a strong influence on the tides of the ocean.",
    "History teaches us how people lived and worked in the past.",
    "Ancient cities were often built next to rivers for fresh water.",
    "Learning a second language opens the door to new cultures.",
    "Practice speaking a little every day, even when it feels difficult.",
    "The teacher explained the grammar rule with several clear examples.",
    "Writing a short summary helps you remember what you have read.",
    "Computers follow instructions that are written by programmers.",
    "A small mistake in the code can cause the whole program to fail.",
    "Always save a backup copy of your important files.",
    "The internet has changed the way we communicate with each other.",
    "Please turn off your phone during the examination.",
    "The meeting has been moved to the large room on the second floor.",
    "Our company is looking for people who enjoy working in a team.",
    "Good communication is the key to a successful project.",
    "The restaurant on the corner serves delicious noodles and rice.",
    "We should leave early to avoid the heavy traffic in the morning.",
    "The hospital is building a new wing for children.",
    "Volunteers cleaned the beach and collected many bags of rubbish.",
    "The festival attracts visitors from many different countries.",
    "Thank you for listening, and see you all next week.",
    "Before we finish, let us review the most important points.",
    "Remember that learning takes time, patience and curiosity.",
    "The bakery opens very early so that people can buy bread on their way to work.",
    "She keeps a small garden on her balcony with herbs and tomatoes.",
    "The bus was late this morning because of an accident on the highway.",
    "He always reads the newspaper while drinking his coffee.",
    "The city council decided to plant more trees along the main avenue.",
    "Our school organizes a science fair at the end of every year.",
    "The students presented their projects to parents and teachers.",
    "A strong wind knocked down several branches in the park.",
    "The farmers are hoping for rain after a long and dry summer.",
    "The old castle on the hill attracts many tourists.",
    "Please remember to bring your identity card to the office.",
    "The pharmacy is next to the post office, across from the bank.",
    "My brother is learning to play the guitar in the evenings.",
    "The concert was cancelled because the singer was sick.",
    "We watched a documentary about the animals of the rainforest.",
    "The ocean covers most of the surface of our planet.",
    "Whales communicate with each other using long and complex songs.",
    "Bees play an important role in growing fruit and vegetables.",
    "The mountain road is closed in winter because of the snow.",
    "Hikers should always carry water, food and a map.",
    "The team celebrated their victory with a big dinner.",
    "The coach reminded the players to rest before the final match.",
    "Our grandparents often tell stories about their childhood.",
    "The village holds a market in the square every weekend.",
    "The chef uses fresh ingredients from local farms.",
    "Please wash your hands before preparing food.",
    "The kitchen smells wonderful when my mother bakes a cake.",
    "The price of vegetables has risen sharply this month.",
    "Saving a little money every week can make a big difference.",
    "The bank offers advice to people who want to buy a house.",
    "The factory hired new workers to meet the growing demand.",
    "Public transport helps reduce pollution in large cities.",
    "More and more people ride bicycles to work.",
    "The government announced a plan to improve rural roads.",
    "Newspapers and websites reported the news within minutes.",
    "The scientist explained her discovery in simple words.",
    "The laboratory needs new equipment for its experiments.",
    "Vaccines have protected millions of people from serious diseases.",
    "The nurse checked the patient's temperature every hour.",
    "A balanced diet includes fruit, vegetables and whole grains.",
    "Walking in nature can reduce stress and improve your mood.",
    "The artist painted the portrait using bright colors.",
    "The theater is presenting a new play this season.",
    "The author signed copies of her latest book at the bookstore.",
    "Poetry often expresses feelings that are difficult to describe.",
    "The photographer waited for hours to capture the sunrise.",
    "The film tells the story of a family that moves to a new country.",
    "Children learn quickly when they are curious and encouraged.",
    "The teacher asked the class to work in pairs.",
    "The final exam will cover everything we have studied this term.",
    "Please submit your essay before the end of the week.",
    "The professor answered questions after the lecture.",
    "Taking regular breaks helps you concentrate for longer.",
    "The robot can sort packages faster than a human worker.",
    "Artificial intelligence is changing many industries.",
    "Engineers are designing cars that use less energy.",
    "The software update fixed several security problems.",
    "Strong passwords protect your accounts from attackers.",
    "The printer on the third floor is out of paper again.",
    "Our internet connection was slow during the storm.",
    "The airport was crowded with travelers during the holidays.",
    "The flight was delayed because of fog.",
    "The hotel room had a beautiful view of the lake.",
    "We rented a small boat and sailed along the coast.",
    "The lighthouse guided ships safely into the harbor.",
    "The fishermen returned to the port with a large catch.",
    "Snow covered the rooftops and the streets were quiet.",
    "The children built a snowman in front of the school.",
    "Autumn leaves turn red, orange and yellow.",
    "The sunset over the sea was absolutely beautiful.",
]
